# Generated by Django 6.0.6 on 2026-07-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='available_hours',
            new_name='available_time',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='biography',
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_case_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='selected_symptoms',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='available_days',
            field=models.CharField(default='Monday to Friday', max_length=100),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='department',
            field=models.CharField(choices=[('GYNECOLOGY', 'General Gynecology'), ('OBSTETRICS', 'Obstetrics & Prenatal Care'), ('FERTILITY', 'Reproductive Endocrinology & Fertility'), ('ONCOLOGY', 'Gynecological Oncology'), ('MENOPAUSE', 'Urogynecology & Menopause Care')], default='GYNECOLOGY', max_length=100),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='hospital_location',
            field=models.CharField(default='BloomCare Clinic, Floor 2, Wing A', max_length=100),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='qualification',
            field=models.CharField(default='MBBS, MD (Obs & Gynae)', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='billinginvoice',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Credit/Debit Card'), ('UPI', 'UPI/Mobile Wallet')], default='CASH', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(default='General Gynecology', max_length=100),
        ),
        migrations.AlterField(
            model_name='labreport',
            name='report_type',
            field=models.CharField(choices=[('ULTRASOUND', 'Ultrasound Imaging'), ('LAB_TEST', 'Lab Diagnostic Test')], max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('DOCTOR', 'Gynecologist (Doctor)'), ('PATIENT', 'Patient')], default='PATIENT', max_length=20),
        ),
    ]
