# Generated by Django 6.0.6 on 2026-07-07 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_available_hours_doctorprofile_available_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labreport',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='labreport',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='menstrualfertilitylog',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='pregnancytrackerlog',
            name='patient',
        ),
        migrations.AlterModelOptions(
            name='appointment',
            options={},
        ),
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='experience_years',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='available_time',
            new_name='work_timings',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='reason_for_visit',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='selected_symptoms',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='available_days',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='hospital_location',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='medical_history_notes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='appointment',
            name='age',
            field=models.PositiveIntegerField(default=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='blood_group',
            field=models.CharField(default='O+', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='height',
            field=models.CharField(default='160 cm', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_name',
            field=models.CharField(default='Anonymous Patient', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='selected_symptom',
            field=models.CharField(default='Pregnancy', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='weight',
            field=models.CharField(default='60 kg', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='age',
            field=models.PositiveIntegerField(default=35),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='hospital_name',
            field=models.CharField(default='BloomCare Hospital', max_length=100),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='working_days',
            field=models.CharField(default='Monday to Saturday', max_length=100),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='gmail',
            field=models.EmailField(default='patient@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.doctorprofile'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_slot',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='department',
            field=models.CharField(choices=[('General Gynecology', 'General Gynecology'), ('Obstetrics', 'Obstetrics'), ('Fertility & IVF', 'Fertility & IVF'), ('Gynecological Oncology', 'Gynecological Oncology'), ('Menopause Care', 'Menopause Care')], default='General Gynecology', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='qualification',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('DOCTOR', 'Doctor'), ('PATIENT', 'Patient')], default='PATIENT', max_length=20),
        ),
        migrations.CreateModel(
            name='LaboratoryTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(choices=[('Blood Test', 'Blood Test'), ('Urine Test', 'Urine Test'), ('Pregnancy Test', 'Pregnancy Test'), ('Hormone Test', 'Hormone Test'), ('Ultrasound Scan', 'Ultrasound Scan'), ('Pelvic Scan', 'Pelvic Scan'), ('Thyroid Test', 'Thyroid Test'), ('Blood Sugar Test', 'Blood Sugar Test'), ('Vitamin D Test', 'Vitamin D Test'), ('CBC Test', 'CBC Test')], max_length=50)),
                ('pdf_report', models.FileField(blank=True, null=True, upload_to='lab_reports/')),
                ('prescribed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Prescribed', max_length=20)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='core.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='PrescribedMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(choices=[('Metformin', 'Metformin'), ('Letrozole', 'Letrozole'), ('Clomiphene', 'Clomiphene'), ('Folic Acid', 'Folic Acid'), ('Iron Tablets', 'Iron Tablets'), ('Calcium Tablets', 'Calcium Tablets'), ('Progesterone', 'Progesterone'), ('Dydrogesterone', 'Dydrogesterone'), ('Tranexamic Acid', 'Tranexamic Acid'), ('Ibuprofen', 'Ibuprofen'), ('Paracetamol', 'Paracetamol'), ('Prenatal Vitamins', 'Prenatal Vitamins')], max_length=50)),
                ('purpose', models.CharField(max_length=150)),
                ('dosage_morning', models.BooleanField(default=False)),
                ('dosage_afternoon', models.BooleanField(default=False)),
                ('dosage_night', models.BooleanField(default=False)),
                ('duration', models.CharField(max_length=50)),
                ('prescribed_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='core.appointment')),
            ],
        ),
        migrations.DeleteModel(
            name='BillingInvoice',
        ),
        migrations.DeleteModel(
            name='LabReport',
        ),
        migrations.DeleteModel(
            name='MedicalRecord',
        ),
        migrations.DeleteModel(
            name='MenstrualFertilityLog',
        ),
        migrations.DeleteModel(
            name='PregnancyTrackerLog',
        ),
    ]
